version: "3.9"
services:
  uroven-admin:
    container_name: uroven-admin
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - PORT=3000
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8n_default"
      - "traefik.http.routers.uroven-admin.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.uroven-admin.entrypoints=websecure"
      - "traefik.http.routers.uroven-admin.tls.certresolver=letsencrypt"
      - "traefik.http.services.uroven-admin.loadbalancer.server.port=3000"
    networks:
      - n8n_default
    # Локальный доступ без Traefik (опционально)
    ports:
      - "3000:3000"

networks:
  n8n_default:
    external: true
    name: n8n_default
